reset file if any error was found, thus preventing faulty commits when forgot to add corections

diff --git a/git_hooks/support/check_for_parse_errors b/git_hooks/support/check_for_parse_errors
--- a/git_hooks/support/check_for_parse_errors
+++ b/git_hooks/support/check_for_parse_errors
@@ -1,18 +1,20 @@
 #!/bin/bash
-
+#set -x
+#set -e
 count=0
 
 red=`tput setaf 1`
 green=`tput setaf 2`
 reset=`tput sgr0`
-
+echo "checking for parse errors"
 for file in $(git diff --cached --name-only --diff-filter=ACM | grep -e '\.php$')
 do
 	if 	php -l ${file}
 	then
 		echo "${green}$file ok${reset}"
 	else
-		echo -e "${red}$file not ok${reset}\n"
+		echo -e "${red}$file not ok, parse errors found, resetting it${reset}\n"
+		git reset ${file}
 		count+=1
 	fi
 done
